# App launchers — edit freely
$terminal = uwsm-app -- alacritty
$browser = uwsm-app -- firefox
$webapp = $browser --new-window
$fileManager = uwsm-app -- nautilus --new-window
$music = uwsm-app -- flatpak run com.spotify.Client
$messenger = uwsm-app -- flatpak run org.signal.Signal
$passwordManager = uwsm-app -- flatpak run com.onepassword.OnePassword

bindd = SUPER, RETURN, Terminal, exec, $terminal
bindd = SUPER, F, File manager, exec, $fileManager
bindd = SUPER, B, Web browser, exec, $browser
bindd = SUPER, M, Music, exec, $music
bindd = SUPER, N, Neovim, exec, $terminal -e nvim
bindd = SUPER, T, Top, exec, $terminal -e btop
bindd = SUPER, D, Lazy Docker, exec, $terminal -e lazydocker
bindd = SUPER, G, Messenger, exec, $messenger
bindd = SUPER, O, Obsidian, exec, uwsm-app -- flatpak run md.obsidian.Obsidian
bindd = SUPER, SLASH, Password manager, exec, $passwordManager
