# Fullscreen screensaver
windowrule = fullscreen on, match:class org.fedorahypr.screensaver
windowrule = float on, match:class org.fedorahypr.screensaver
windowrule = animation slide, match:class org.fedorahypr.screensaver
