# App-specific tweaks
source = /usr/share/fedora-hypr/default/hypr/apps/1password.conf
source = /usr/share/fedora-hypr/default/hypr/apps/browser.conf
source = /usr/share/fedora-hypr/default/hypr/apps/hyprshot.conf
source = /usr/share/fedora-hypr/default/hypr/apps/localsend.conf
source = /usr/share/fedora-hypr/default/hypr/apps/pip.conf
source = /usr/share/fedora-hypr/default/hypr/apps/system.conf
source = /usr/share/fedora-hypr/default/hypr/apps/terminals.conf
source = /usr/share/fedora-hypr/default/hypr/apps/walker.conf
source = /usr/share/fedora-hypr/default/hypr/apps/webcam-overlay.conf
