# Adapted from third-party MIT-licensed code; see LICENSE-THIRD-PARTY in the source repo
exec-once = systemctl --user import-environment $(env | cut -d'=' -f 1)
exec-once = uwsm-app -- hypridle
exec-once = uwsm-app -- mako
exec-once = ! fh-toggle-enabled waybar-off && uwsm-app -- waybar
exec-once = uwsm-app -- fcitx5 --disable notificationitem
exec-once = uwsm-app -- swaybg -i ~/.config/fedora-hypr/current/background -m fill
exec-once = uwsm-app -- elephant
exec-once = uwsm-app -- env GSK_RENDERER=cairo walker --gapplication-service
exec-once = systemctl --user start hyprpolkitagent.service
exec-once = uwsm-app -- swayosd-server
exec-once = fh-first-run
exec-once = fh-powerprofiles-init
exec-once = systemctl --user start podman.socket
exec-once = uwsm-app -- fh-hyprland-monitor-watch
