# Menus
bindd = SUPER, SPACE, Launch apps, exec, fh-launch-walker
bindd = SUPER CTRL, E, Emoji picker, exec, fh-launch-walker -m symbols
bindd = SUPER CTRL, C, Capture menu, exec, fh-menu capture
bindd = SUPER CTRL, O, Toggle menu, exec, fh-menu toggle
bindd = SUPER CTRL, H, Hardware menu, exec, fh-menu hardware
bindd = SUPER ALT, SPACE, fedora-hypr menu, exec, fh-menu
bindd = SUPER SHIFT, code:201, fedora-hypr menu, exec, fh-menu
bindd = SUPER, ESCAPE, System menu, exec, fh-menu system
bindld = , XF86PowerOff, Power menu, exec, fh-menu system
bindd = SUPER, K, Show key bindings, exec, fh-menu-keybindings
bindd = , XF86Calculator, Calculator, exec, gnome-calculator

# Aesthetics
bindd = SUPER SHIFT, SPACE, Toggle top bar, exec, fh-toggle-waybar
bindd = SUPER CTRL, SPACE, Theme background menu, exec, fh-menu background
bindd = SUPER SHIFT CTRL, SPACE, Theme menu, exec, fh-menu theme
bindd = SUPER, BACKSPACE, Toggle window transparency, exec, fh-hyprland-window-transparency-toggle
bindd = SUPER SHIFT, BACKSPACE, Toggle window gaps, exec, fh-hyprland-window-gaps-toggle
bindd = SUPER CTRL, BACKSPACE, Toggle single-window square aspect, exec, fh-hyprland-window-single-square-aspect-toggle

# Notifications
bindd = SUPER, COMMA, Dismiss last notification, exec, makoctl dismiss
bindd = SUPER SHIFT, COMMA, Dismiss all notifications, exec, makoctl dismiss --all
bindd = SUPER CTRL, COMMA, Toggle silencing notifications, exec, fh-toggle-notification-silencing
bindd = SUPER ALT, COMMA, Invoke last notification, exec, makoctl invoke
bindd = SUPER SHIFT ALT, COMMA, Restore last notification, exec, makoctl restore

# Toggles
bindd = SUPER CTRL, I, Toggle locking on idle, exec, fh-toggle-idle
bindd = SUPER CTRL, N, Toggle nightlight, exec, fh-toggle-nightlight
bindd = SUPER CTRL, Delete, Toggle laptop display, exec, fh-hyprland-monitor-internal toggle
bindd = SUPER CTRL ALT, Delete, Toggle laptop display mirroring, exec, fh-hyprland-monitor-internal-mirror toggle
bindl = , switch:on:Lid Switch, exec, fh-hw-external-monitors && fh-hyprland-monitor-internal off
bindl = , switch:off:Lid Switch, exec, fh-hyprland-monitor-internal on

# Captures
bindd = , PRINT, Screenshot, exec, fh-capture-screenshot
bindd = ALT, PRINT, Screenrecording, exec, fh-menu screenrecord
bindd = SUPER, PRINT, Color picker, exec, pkill hyprpicker || hyprpicker -a
bindd = SUPER CTRL, PRINT, Extract text (OCR) from screenshot, exec, fh-capture-text-extraction

# File sharing
bindd = SUPER CTRL, S, Share, exec, fh-menu share

# Transcoding
bindd = SUPER CTRL, PERIOD, Transcode, exec, fh-transcode

# Reminders
bindd = SUPER CTRL, R, Set reminder, exec, fh-menu reminder-set
bindd = SUPER CTRL ALT, R, Show reminders, exec, fh-reminder show
bindd = SUPER SHIFT CTRL, R, Clear reminders, exec, fh-reminder clear

# Waybar-less information
bindd = SUPER CTRL ALT, T, Show time, exec, notify-send -u low "    $(date +"%A %H:%M  ·  %d %B %Y  ·  Week %V")"
bindd = SUPER CTRL ALT, B, Show battery remaining, exec, notify-send -u low "$(fh-battery-status)"
bindd = SUPER CTRL ALT, W, Show weather, exec, notify-send -u low "$(fh-weather-status)"

# Control panels
bindd = SUPER CTRL, A, Audio controls, exec, fh-launch-audio
bindd = SUPER CTRL, B, Bluetooth controls, exec, fh-launch-bluetooth
bindd = SUPER CTRL, W, Wifi controls, exec, fh-launch-wifi
bindd = SUPER CTRL, T, Activity, exec, fh-launch-tui btop

# Zoom
bindd = SUPER CTRL, Z, Zoom in, exec, hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float + 1')
bindd = SUPER CTRL ALT, Z, Reset zoom, exec, hyprctl keyword cursor:zoom_factor 1

# Lock system
bindd = SUPER CTRL, L, Lock system, exec, fh-system-lock
